name: amap_location_example
description: Demonstrates how to use the amap_location plugin.

dependencies:
  flutter:
    sdk: flutter

  async_loader:
  
  cupertino_icons: ^0.1.0
  simple_permissions:
  easy_alert:

dev_dependencies:
  flutter_test:
    sdk: flutter

  amap_location:
    path: ../

flutter:
  uses-material-design: true
